const QUOTES = [
  { q: "I am grateful for the simple moments that remind me life is beautiful." },
  { q: "I am grateful for the people who believed in me before I believed in myself." },
  { q: "I am grateful for every challenge that made me stronger and wiser." },
  { q: "I am grateful for the warmth of the sun, the breath in my lungs, and the beat of my heart." },
  { q: "I am grateful for second chances and the courage to take them." },
  { q: "I am grateful for the laughter that fills my life and the friends who bring it." },
  { q: "I am grateful for mornings that offer a fresh start and a new perspective." },
  { q: "I am grateful for the lessons hidden in my hardest days." },
  { q: "I am grateful for the small acts of kindness that restore my faith in people." },
  { q: "I am grateful for the gift of curiosity that keeps me learning and growing." },
  { q: "I am grateful for quiet moments of peace in the middle of a busy world." },
  { q: "I am grateful for the strength I discovered when I thought I had none left." },
  { q: "I am grateful for every person who has loved me without condition." },
  { q: "I am grateful for the dreams that push me forward and give my life direction." },
  { q: "I am grateful for the food on my table, the roof over my head, and the warmth of belonging." },
  { q: "I am grateful for music that speaks when words cannot." },
  { q: "I am grateful for the stories I carry and the ones I have yet to write." },
  { q: "I am grateful for nature's reminder that beauty exists in every season." },
  { q: "I am grateful for the mentors who gave their time so I could find my way." },
  { q: "I am grateful for rest, for healing, and for the patience to let both happen." },
  { q: "I am grateful for the courage to be myself, even when it felt difficult." },
  { q: "I am grateful for every small win that kept me going on the hardest days." },
  { q: "I am grateful for the conversations that changed the way I see the world." },
  { q: "I am grateful for love in all its forms — given, received, and growing." },
  { q: "I am grateful for this moment, exactly as it is." },
  { q: "I am grateful for my body and all it does for me every single day." },
  { q: "I am grateful for the joy I feel in doing what I love." },
  { q: "I am grateful for hope — the quiet belief that better days are always ahead." },
  { q: "I am grateful for the abundance in my life, seen and unseen." },
  { q: "I am grateful for today, for it is a gift I will never have again." },
  { q: "I am grateful for the creativity that flows through me when I trust myself." },
  { q: "I am grateful for the tears that cleansed me and the joy that followed." },
  { q: "I am grateful for every door that closed, because it led me somewhere better." },
  { q: "I am grateful for the kindness of strangers that reminds me we are all connected." },
  { q: "I am grateful for the comfort of home and the safety it brings." },
  { q: "I am grateful for patience — mine and that of those who waited for me." },
  { q: "I am grateful for the ability to change my mind and grow beyond who I was." },
  { q: "I am grateful for every sunrise that gives me another chance to begin again." },
  { q: "I am grateful for the friendships that feel like home no matter the distance." },
  { q: "I am grateful for my intuition that guides me even when the path is unclear." },
  { q: "I am grateful for the silence that lets me hear what truly matters." },
  { q: "I am grateful for the progress I have made, no matter how small it may seem." },
  { q: "I am grateful for every experience that shaped me into who I am today." },
  { q: "I am grateful for the freedom to choose how I respond to life's challenges." },
  { q: "I am grateful for the mentors, teachers, and guides who walked beside me." },
  { q: "I am grateful for my unique journey and everything it has taught me." },
  { q: "I am grateful for laughter — the kind that comes from deep in the belly and heals the soul." },
  { q: "I am grateful for the love I have given and the love that has found its way back to me." },
];

export async function GET() {
  const quote = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  return Response.json(quote);
}
